//created by swakil

if ( balanceDue <= 0 && !(AInfo["Paying with Bond"] == 'Yes') )
{
	updateTask("Permit Issued", "Awaiting Approval", "EMSE", "Script");
	addPendingInspection("ECKO and Initial Inspection", "Generated by EMSE");
	
	var reportname = "JD_TEST_REPORT";
	var template = "JD_TEST_TEMPLATE";
	var contact = "Applicant";
	var joke = "Where there's a will, there's a relative.";

	var emailparams = aa.util.newHashtable();
	emailparams.put("$$Joke$$", joke);
	var reportparams = aa.util.newHashtable();
	reportparams.put("DEPARTMENT", "Administrator");
	emailContacts(contact, template, emailparams, reportname, reportparams, "N", "");
	
}

function addPendingInspection(iType, inspComm) {
    var inspId = 0;
    var inspectorObj = null;
    var inspTime = null;

    var schedRes = aa.inspection.scheduleInspection(capId, inspectorObj, aa.date.parseDate(dateAdd(null, 0)), inspTime, iType, inspComm);

    if (schedRes.getSuccess()) {
        inspId = schedRes.output;
        aa.print("inspId = " + inspId);

        var justScheduled = aa.inspection.getInspection(capId, inspId);

        if (justScheduled.getSuccess()) {
            var inspModel = justScheduled.getOutput();

            inspModel.setInspectionStatus("Pending");
            aa.inspection.editInspection(inspModel);
        }
        else {
            aa.print("Failed to get inspection.");
        }

        logDebug("Successfully scheduled pending inspection : " + iType);
    } else {
        logDebug("**ERROR: adding pending scheduling inspection (" + iType + "): " + schedRes.getErrorMessage());
    }
}
